<a href="https://colab.research.google.com/github/Bkevz/Data-Analytics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy
numpy.  __version__

'1.22.4'

Array initiliazation using numpy -single dimensional

In [ ]:
import numpy as np
a = np.array([5,9,9,4])
print(a)

[5 9 9 4]


Multidimensional array _ matrix

In [ ]:
import numpy as np
b = np.array([(5,9,9,4),(4,6,8,3)])
print(b)

[[5 9 9 4]
 [4 6 8 3]]


Generating arrays

In [ ]:
import numpy as np
c = np.arange(10) #range of values in array
d = np. linspace(1,10,5) #set of values by interval [start,end,no.of valuesEqualInterval]
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [9]:
import numpy as np
a = np.array ([(7,9,25,16), (24,64,14,19)])
b = np.array([(10,56,81,74), (34,56,95,73)])
print(b.sum(axis=0))#sum of dimensio of 1 and 2 elements
print(b.sum(axis=1)) #sum of a elements from dim 1 and 2 seperately
print(np.sqrt(a)) #squaroot
print(np.std(a)) #standard deviation
print(np.exp(a)) #exponential
print(np.log(a)) #natural log
print(np.log10(a)) #log base 10

print(np.vstack((a,b))) # vertical stack
print(np.hstack((a,b))) #horizontally stack
print(a.ravel()) #combining as one dimenision

[ 44 112 176 147]
[221 258]
[[2.64575131 3.         5.         4.        ]
 [4.89897949 8.         3.74165739 4.35889894]]
16.880091824394796
[[1.09663316e+03 8.10308393e+03 7.20048993e+10 8.88611052e+06]
 [2.64891221e+10 6.23514908e+27 1.20260428e+06 1.78482301e+08]]
[[1.94591015 2.19722458 3.21887582 2.77258872]
 [3.17805383 4.15888308 2.63905733 2.94443898]]
[[0.84509804 0.95424251 1.39794001 1.20411998]
 [1.38021124 1.80617997 1.14612804 1.2787536 ]]
[[ 7  9 25 16]
 [24 64 14 19]
 [10 56 81 74]
 [34 56 95 73]]
[[ 7  9 25 16 10 56 81 74]
 [24 64 14 19 34 56 95 73]]
[ 7  9 25 16 24 64 14 19]
